---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
runson: mac
autosplit: true
retryOnFailure: true
maxRetries: 1
concurrency: 1
env:
 TARGET_OS: "MacOS Catalina"
cacheKey: '{{ checksum "requirement.txt" }}'
cacheDirectories:
  - CacheDir
pre:
  - npm install playwright@1.24.0 --save-exact
  - pip install -r requirement.txt --cache-dir CacheDir
  - playwright install
testDiscovery:
  type: raw
  mode: dynamic
  command: grep -lr 'def' *.py
testRunnerCommand: pytest $test
post:
  - cat yaml/win/.hyperexecute_autosplits.yaml